version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      # comments
      - ./gradlew shadowJar
  post_build:
    commands:
      - echo Build completed
      - aws lambda update-function-code --function-name test-java --zip-file fileb://build/distributions/my-lambda-function-all.jar