version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      # comments
      - ./gradlew build
  post_build:
    commands:
      - echo Build completed on `date`
      - aws lambda update-function-code --function-name test-java --zip-file fileb://build/distributions/java-github-to-lambda.zip